# Title of the workflow.
name: Atoum

# Run this workflow every time a new commit pushed to your repository or PR created.
on: [push, pull_request]

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided.
  test:
    # Virtual environment to use.
    runs-on: ubuntu-22.04

    # Determines build matrix.
    strategy:
      fail-fast: false
      matrix:
        php: ['8.2', '8.3', '8.4']

    steps:
      # Check out this repository code in ./plugin directory
      - name: Check out repository code
        uses: actions/checkout@v2

      # Install PHP of required version. For possible options see https://github.com/shivammathur/setup-php
      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      # Initialise composer.
      - name: Initialise composer
        run: |
          cp distribution/config.php .
          composer install

      # Run atoum.
      - name: Run Atoum.
        run: |
          php vendor/bin/atoum -d tests/unit/classes/ -af .atoum.php

      # Run regression tests.
      - name: Run regression tests.
        run: |
          cp distribution/config.php .
          php tests/regression/run.php
